baseURL = "https://www.cxmoe.com/cls_aiLearn/"
languageCode = "zh-CN"
title = "cls_aiLearn"
contentDir = "posts"

theme = "oink"

[markup.goldmark.renderer]
  unsafe = true
[markup.goldmark.parser]
  wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
  block = true

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[params]
  reading_width = "normal"
  offline_search = true
